# Site settings
title: Zachary Lloyd Jones
description: Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zachary Lloyd Jones
user_description: I'm an integration specialist and software developer.  
user_title: Integration Specialist
email: zack@zackjones.net
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
