# Site settings
title: Zachary Lloyd Jones
description: Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zackjones.net" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zachary Lloyd Jones
user_description: I'm an integration specialist and software developer.  
user_title: Integration Specialist
email: zack@zackjones.net
twitter_username: https://twitter.com/weatwagon
github_username:  https://github.com/Weatwagon
linkedin_username:  https://www.linkedin.com/in/zachary-l-jones/
instagram_username:  https://www.instagram.com/weatwagon/
facebook_username:  https://www.facebook.com/weatwagon
#gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
